# Site settings
title: Sabine Werthmann
subtitle: Systemische Einzel-, Paar- und Familientherapie
description: ""
url: "http://familientherapie-werthmann.de"

# Build settings
markdown: kramdown
exclude:
  - "bower_components"
  - "bower.json"
include:
  - "bower_components/foundation-sites/dist/foundation.min.js"
