# Site settings
title: Sabine Werthmann
subtitle: Systemische Einzel-, Paar- und Familientherapie
description: "Sabine Werthmann, Systemische Einzel-, Paar- und Familientherapie"
url: "http://familientherapie-werthmann.de"

# Build settings
markdown: kramdown
exclude:
  - "bower_components"
  - "bower.json"
# include:

collections:
  - inhalt